# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  build:
    cmds:
      - go build -o logging-exp ./cmd/logging-exp
      - go clean -testcache
      - go test -v ./internal/test/... -run=^_$
      - go test -v ./internal/benchmark/... -bench=^_$

  bench-logging:
    cmds:
      - go clean -testcache
      - go test -v ./internal/benchmark/... -benchmem -bench=^BenchmarkCalculateWithLogging$ -cpuprofile prof_logging.out
      - go tool pprof -http=":9080" logging-exp prof_logging.out
      
  bench-nologging:
    cmds:
      - go clean -testcache
      - go test -v ./internal/benchmark/... -benchmem -bench=^BenchmarkCalculateWithoutLogging$ -cpuprofile prof_nologging.out
      - go tool pprof -http=":9081" logging-exp prof_nologging.out
      
  test:
    cmds:
      - go clean -testcache
      - go test -v ./internal/test/... -run=^TestRunnerRun$